changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Bug 🛠
      labels:
        - bug
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Documentation
      labels: 
        - documentation
    - title: Other Changes
      labels:
        - "*"
